### ISSUE TITLE
Connect with agencies (NOAA, USGS, USFW, ect) and asses their needs

### ISSUE THREAD

**Issue by hdolinh** [hdolinh/learning-hub-onboarding#121]

**Comment by camilavargasp** [comment]
- #22

**Comment by hdolinh** [comment]
From focus group report:

- work with those who have access to funding for professional development
- openscapes training
- provide curated training

**Comment by hdolinh** [comment]
Start with USGS:

- have already worked with DataONE
- have created lots of resources (see DMT Clearinghouse)
- in recent years and especially not, have increased interest in leveraging data in their work

**Comment by hdolinh** [comment]
> * #22

I deleted issue #22 and copied the comments over to this issue

**Comment by hdolinh** [comment]
Courtney reached out to the following organizations for the UC California Climate Action RFP LOI: 

- LTER LNO - CONFIRMED 
- CA DFW - CONFIRMED
- SF BCDC - CONFIRMED/more conversations following LOI
- CA Natural Resources Agency 
- Dept Water Resources - CONFIRMED
- Department of Conservation
- Coastal Commission
- Delta Stewardship Council
