### ISSUE TITLE
Ask Jeanette about how to use DataONE data managment courses and learning material

### ISSUE THREAD

**Issue by camilavargasp** [hdolinh/learning-hub-onboarding#26]

**Comment by camilavargasp** [comment]
- DataONE has not done a workshop in a while
- Amber is the person to ask about
- Have as a resource to point to and to be aware of that exist
- Ask Matt for more details on DataONE training

**Comment by hdolinh** [comment]
**Next step:**

- [x] Ask Matt about how to collaborate / incorporate DataOne Trainings

**Comment by hdolinh** [comment]
[Data Management Skillbuilding Hub](https://dataoneorg.github.io/Education/)
[Data Management Training](https://www.dataone.org/training/) (training dates and language needs to be updated)

**Comment by hdolinh** [comment]
Big takeaway from meeting with Matt: DataOne significantly supported the creation of LH financially and programmatically. Moving forward training resources should be absorbed, managed and maintained by LH but we should allow for co-branding between DataOne and LH.
