### ISSUE TITLE
Strategic Planning meeting thoughts

### ISSUE THREAD

**Issue by camilavargasp** [hdolinh/learning-hub-onboarding#31]
Think about how each program LTER, ADC, etc, keep their own identity vs what is the learning hub.
The Learning Hub is the umbrella that host each of the learning resources developed by each of these programs.

- Is there a unifying line? What would that be?
- Should we have one staple on how each learning material should be developed?
- Advantages and disadvantages of having "templates" ?
- How do we streamline but also allow the personal creativity of anyone who is creating material?
- What are people's experiences when creating workshops?

Looking at [scicomp-workshop-template](https://github.com/NCEAS/scicomp-workshop-template) made me think about all these.

**Comment by camilavargasp** [comment]
**Terminology**
 How to refer to what?
It might be beneficial to define what is what. For example, a long workshop v/s a modular workshop. Or training vs. workshop.
I think of _long workshop_  (or training?) as multiple days just dedicated to learning. For example, the 5 days reproducible science workshop.
A modular workshop  is one module within the curriculum of the long workshop,
We can create packages of modular workshops that go together with each other.

**Comment by hdolinh** [comment]
[LH Strategic Planning Meeting occurred 11/10](https://docs.google.com/document/d/1Hp3_wnw9dMnPAYC3S3ZoesrF8OxYrzmTYjhgKuc-rmM/edit)
