### ISSUE TITLE
Create outreach list for promoting CORE R Course

### ISSUE THREAD

**Issue by hdolinh** [hdolinh/learning-hub-onboarding#37]
- Consider outreach list for all courses and workshops at NCEAS
- Identify which communities are relevant to promote ADC
- Identify which communities are relevant to promote MEDS

**Comment by camilavargasp** [comment]
[Here the growing list](https://docs.google.com/spreadsheets/d/1NiTNEnNaBq3bCIpkHLUJmBu5FBlEsjqIeVK-XcRRayM/edit#gid=1803696035)
