### ISSUE TITLE
Create Canva Flyer

### ISSUE THREAD

**Issue by hdolinh** [hdolinh/learning-hub-onboarding#39]
- [ ] Get Canva Pro access from Thomas

**Comment by camilavargasp** [comment]
Old versions

![Image](https://user-images.githubusercontent.com/35848897/207178887-07380411-be5e-413d-aa96-107225f13da7.png)

**Comment by camilavargasp** [comment]
Social Media post version 1

![Image](https://user-images.githubusercontent.com/35848897/207179154-56bf9118-dd0c-4949-aa38-c052a6e41c51.png)

**Comment by hdolinh** [comment]
[coreR-2023-04-NCEAS.pdf](https://github.com/hdolinh/learning-hub-onboarding/files/10482332/coreR-2023-04-NCEAS.pdf)
