### ISSUE TITLE
Reach out to past participants and collect testimonies

### ISSUE THREAD

**Issue by hdolinh** [hdolinh/learning-hub-onboarding#41]
This includes asking past participants to promote CORE R April Course with their networks (i.e. retweeting on Twitter)

- [x] Ask Jeanette / Courtney about where past participant info is

**Comment by camilavargasp** [comment]
Courtney provided past participants' quotes. See the following documents
- [Training testimonial](https://docs.google.com/document/d/1L7R_y7v4n-VltsMqdWvsIaKSUmWX6ZmR3EO3h6FOTe4/edit)
- [Testimonial Bank of quotes](https://docs.google.com/spreadsheets/d/10mU7FTXbsFg1RYbUdZHlr3HozH6AfhhBcjsUu2BLORQ/edit#gid=2082563450)

**Comment by camilavargasp** [comment]
**notes**
- The testimonial Bank of quotes is specifically centered on Synthesis science.
- In the Training testimonial file, there are a couple of good quotes from the most recent trainings.  [See this Wiki](https://github.com/hdolinh/learning-hub-onboarding/wiki/Testimonial-quotes-selection--by-audience).


I think it wold be good to talk to Jeanette about this.

**Comment by hdolinh** [comment]
Did not reach out to past participants this time. Will rethink strategy for next time.
