### ISSUE TITLE
Ask Courtney about CORE R April Course discount opportunities 

### ISSUE THREAD

**Issue by hdolinh** [hdolinh/learning-hub-onboarding#42]
- For example: 10% discount for UCSB students or UCSB alumni
- Partial funding?
- Second Director's Scholarship for a local participant or student?

**Comment by hdolinh** [comment]
Going to get update next week (11/28) after Courtney talks to Ben

**Comment by camilavargasp** [comment]
- For the April course, we will go with the Directorship Scholarship.
- Past April, we can think of other discount options
- In the new year, we need to have a budgeting and finances meeting and do a cost model to see what is possible
