### ISSUE TITLE
How important is to NCEAS that we are tracking demographics of attendees?

### ISSUE THREAD

**Issue by hdolinh** [hdolinh/learning-hub-onboarding#6]

**Comment by hdolinh** [comment]
Get qualitrics account: https://ucsb.co1.qualtrics.com/homepage/ui

**Comment by camilavargasp** [comment]
- they do collect demographic data
- Long-term data is under Amber's Qualitrics account
- We should try to get at least anonymous before

**Comment by hdolinh** [comment]
Addressed at LH Strategic Planning Meeting
