### ISSUE TITLE
Research other EDS Programs

### ISSUE THREAD

**Issue by hdolinh** [hdolinh/learning-hub-onboarding#7]

**Comment by hdolinh** [comment]
[DataONE](https://www.dataone.org/) Learning tab has the following options: [skill building](https://dataoneorg.github.io/Education/), [webinars](https://www.dataone.org/webinars/), [training](https://www.dataone.org/training/), [portals how-to](https://www.dataone.org/portals-tutorial/)

**Comment by hdolinh** [comment]
[Data Management Training (DMT) Clearinghouse](https://dmtclearinghouse.esipfed.org/search/dmt)

- DataONE trainings are listed here
- USGS seems to be providing a lot of trainings (might be a good agency to start building a partnership with since they have started data efforts?)
- Most trainings are focused on **Data Management** 
- Most trainings use the **FAIR Data Principles** framework
- ~50 organizations feature trainings or resources here, with Federation of Earth Science Information Partners (ESIP Federation) having contributed the most
- People (trainers?) are also listed and search can be filtered by person(s)
- Only 1 training has been added in 2022 (maybe the site is not being as used anymore?)

**Comment by hdolinh** [comment]
WiDS

**Comment by hdolinh** [comment]
Other UC Data Science Hubs (i.e. UC Davis)

**Comment by hdolinh** [comment]
Earth Lab

**Comment by camilavargasp** [comment]
- [Here the spreadsheet](https://docs.google.com/spreadsheets/d/1y5_7cpGG1eb56cnMZl9sb-AbfaSCc3hidZjs5L7VZoA/edit#gid=989197081) where this list lives

**Comment by hdolinh** [comment]
Will add to spreadsheet as needed; section created in LH Manual
